config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#top'
  get 'tweets/top' => 'tweets#top'
  resources :tweets
  resources :users  ,:only => :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: [:top, :index, :edit, :show]

  def top
  end

  def index
    @tweets = Tweet.order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @tweet = Tweet.new
  end

  def show
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
       tweet.destroy
       redirect_to action: :index
    end
  end

  def create
    Tweet.create(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
       tweet.destroy
    end
  end

  def edit
      @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
       tweet.update(tweet_params)
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text, :image, :title).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :top unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <style type="text/css" href="./style.css"></style>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
  <style >
    body{
      background-image: url("gogoame.pdf");
    }
    .clearfix:after {
        clear: both;
        content: '';
        display: block;
      }

  </style>
</head>

 <body>
  <header>
<!-- /header -->
    <nav class = "indigo lighten-1">
     <div class="nav-wrapper">
      <a href="/tweets/top" class="brand-logo right"> right as rain </a>
       <ul id="nav-mobile" class="left hide-on-med-and-down">
        <% if user_signed_in? %>
         <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
          <li><a href="/tweets/new">HOW WAS YOUR DAY? </a></li>
         <% else %>
          <li><%= link_to "LOG IN", new_user_session_path, class: 'post' %></li>

          <li class="active"><%= link_to "NEW ACCOUNT", new_user_registration_path, class: 'post' %></li>
        <% end %>
       </ul>
     </div>
    </nav>
  </header><!-- /header -->

    <%= yield %>

  <footer class = "indigo lighten-1">

   <div class="footer-copyright">
    <div class="container">
       Copyright BlogApp 2018.by YOKO.
    </div>
   </div>
  </footer>
 </body>
</html>

app/views/tweets/_tweets.html.erb
<div class = "container clearfix">
  <div class="row amber lighten-3">
    <div class="row">
    <div class="col s4 m7">
    </div>
    <div class="col s8 m7">
      <div class="card">
        <div class="card-image container">
          <img src="<%= tweet.image%>">
           <span class="card-title"><%= tweet.title %></span>
        </div>
        <div class="card-content container">
          <%= simple_format(tweet.text) %>
        </div>
        <div class="card-action container">
          <% if user_signed_in? && current_user.id == tweet.user_id %>
          <%= link_to "EDIT", edit_tweet_path(tweet[:id]) , method: :patch, class: "cwaves-effect waves-light btn" %>
          <%= link_to "DELETE" , "/tweets/#{tweet.id}", method: :delete, class: "cwaves-effect waves-light btn"%>
          <% end %>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      I'm glad that you seem to have had a good day！<br>
      I hope that tomorrow will also a good day.
    </h3>
    <a class="waves-effect waves-light btn" href="/tweets">Go To Index</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">

  <%= form_for @tweet do |f|%>
    <%= f.label :HOW_WAS_YOUR_DAY?, style: { 'margin-right' => 8 } %>
    <%= f.text_field :title, placeholder: "TITLE", class: "form-control"%>
    <%= f.text_field :text, placeholder: "TEXT", class: "form-control" %>
    <%= f.text_field :image, placeholder: "IMAGE_URL", class: "form-control" %>
    <%= f.submit "Let's Repost It!", class: "btn btn-primary withripple" %>
  <% end %>
</div>

app/views/tweets/index.html.erb
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweets", locals: { tweet: tweet } %>
  <% end %>

  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <%= form_for @tweet do |f|%>
    <%= f.label :HOW_WAS_YOUR_DAY?, style: { 'margin-right' => 8 } %>
    <%= f.text_field :title, placeholder: "TITLE", class: "form-control" %>
    <%= f.text_field :text, placeholder: "TEXT", class: "form-control" %>
    <%= f.text_field :image, placeholder: "IMAGE_URL", class: "form-control" %>
    <%= f.submit "Let's post it!", class: "btn btn-primary withripple" %>
    <% end %>
</div>

app/views/tweets/top.html.erb
<iframe id="inlineFrameExample"
  title="Inline Frame Example"
  width="100%"
  height="960px"
  src="http://gogoame.sumbioun.com/">
</iframe>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      Update has been completed.
    </h3>
    <a class="btn light-blue darken-3" href="/tweets">Go To Index.</a>
  </div>
</div>